<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Scout</title>
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    <?php
    echo $this->tag->stylesheetLink('/scout_app/public/css/bootstrap/bootstrap.min.css');
    echo $this->tag->stylesheetLink("https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css", false);
    echo $this->tag->stylesheetLink('/scout_app/public/css/style.css');
    echo $this->tag->javascriptInclude('/scout_app/public/js/jquery.min.js');
    echo $this->tag->javascriptInclude("https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js");
    echo $this->tag->javascriptInclude('/scout_app/public/js/bootstrap/bootstrap.min.js');
    echo $this->tag->javascriptInclude("https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js", false);
    echo $this->tag->javascriptInclude('/scout_app/public/js/validate.js');
    
    ?>
</head>
<body>
    <div class="container">
        <?php echo $this->getContent(); ?>
    </div>
</body>
</html>
